image: python:3.8.8

before_script:
    - pip install mkdocs-material
    # - pip install . # install the prismpyp package to generate cli docs

docs:
  stage: deploy
  script:
    - mkdocs build --strict --verbose
    # - mkdocs build --verbose
  artifacts:
    paths:
      - public
  only:
    # only run this CI pipeline on master
    refs:
      - cryosparc_reupload