image: python:3.12

before_script:
    - pip install mkdocs-material
    - pip install . # install the prismpyp package to generate cli docs

docs:
  stage: deploy
  script:
    - python scripts/gen_cli_docs.py # generate cli docs
    - mkdocs build --strict --verbose
    # - mkdocs build --verbose
  artifacts:
    paths:
      - public
  only:
    # only run this CI pipeline on master
    refs:
      - website