channels:
  - pytorch
  - nvidia
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.12
  - numpy=1.26
  - mrcfile
  - umap-learn
  - faiss-gpu=1.9.0
  - matplotlib
  - ca-certificates
  - certifi
  - openssl
  - opencv
  - pandas
  - seaborn
  - ipykernel
  - pyarrow
  - toml
  - ipywidgets
  - plotly
  - anywidget
  - pytorch-cuda=12.1
  - matplotlib-venn
  - scikit-image
  - pytorch
  - torchvision
  - tensorboard
  - wandb
